vim.keymap.set('n', '<leader>gs', vim.cmd.Git)
vim.keymap.set("n", "<leader>ga", function()
	vim.cmd("Git add .")
end)
vim.keymap.set("n", "<leader>gc", function()
	vim.cmd("Git commit")
end)
vim.keymap.set("n", "<leader>gpo", function()
	local branch = vim.fn.trim(vim.fn.system("Git branch --show-current"))
        vim.cmd("Git push origin " .. branch)
end)
